name: Auto Pull Request for Homework

on:
  push:
    branches:
      - add/hw*

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: main
          title: '${GITHUB_REF##*/} PR (automated)'
          body: 'This pull request is for changes in `${GITHUB_REF##*/}`'
          labels: 'homework'
          draft: false
