name: Auto-Merge Practice Files

on:
  push:
    branches:
      - practice/*

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge changes into main
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout main
          git merge practice --no-ff --commit
          git push origin main
